# Generated by Django 4.2.8 on 2024-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nifty_50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('market_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nifty_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('market_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nifty_finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('market_cap', models.IntegerField()),
            ],
        ),
    ]
